/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminRouteImport } from './routes/termin'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BeratungRouteImport } from './routes/beratung'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSlugRouteImport } from './routes/services_.$slug'
import { Route as ApiPublicConsultationManageRouteImport } from './routes/api/public/consultation-manage'
import { Route as ApiPublicConsultationCallbackRouteImport } from './routes/api/public/consultation-callback'
import { Route as ApiPublicConsultationBookingRouteImport } from './routes/api/public/consultation-booking'
import { Route as ApiPublicCareersApplicationRouteImport } from './routes/api/public/careers-application'

const TerminRoute = TerminRouteImport.update({
  id: '/termin',
  path: '/termin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BeratungRoute = BeratungRouteImport.update({
  id: '/beratung',
  path: '/beratung',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services_/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConsultationManageRoute =
  ApiPublicConsultationManageRouteImport.update({
    id: '/api/public/consultation-manage',
    path: '/api/public/consultation-manage',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConsultationCallbackRoute =
  ApiPublicConsultationCallbackRouteImport.update({
    id: '/api/public/consultation-callback',
    path: '/api/public/consultation-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConsultationBookingRoute =
  ApiPublicConsultationBookingRouteImport.update({
    id: '/api/public/consultation-booking',
    path: '/api/public/consultation-booking',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCareersApplicationRoute =
  ApiPublicCareersApplicationRouteImport.update({
    id: '/api/public/careers-application',
    path: '/api/public/careers-application',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beratung': typeof BeratungRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/imprint': typeof ImprintRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termin': typeof TerminRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/api/public/careers-application': typeof ApiPublicCareersApplicationRoute
  '/api/public/consultation-booking': typeof ApiPublicConsultationBookingRoute
  '/api/public/consultation-callback': typeof ApiPublicConsultationCallbackRoute
  '/api/public/consultation-manage': typeof ApiPublicConsultationManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beratung': typeof BeratungRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/imprint': typeof ImprintRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termin': typeof TerminRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/api/public/careers-application': typeof ApiPublicCareersApplicationRoute
  '/api/public/consultation-booking': typeof ApiPublicConsultationBookingRoute
  '/api/public/consultation-callback': typeof ApiPublicConsultationCallbackRoute
  '/api/public/consultation-manage': typeof ApiPublicConsultationManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beratung': typeof BeratungRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/imprint': typeof ImprintRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termin': typeof TerminRoute
  '/services_/$slug': typeof ServicesSlugRoute
  '/api/public/careers-application': typeof ApiPublicCareersApplicationRoute
  '/api/public/consultation-booking': typeof ApiPublicConsultationBookingRoute
  '/api/public/consultation-callback': typeof ApiPublicConsultationCallbackRoute
  '/api/public/consultation-manage': typeof ApiPublicConsultationManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/beratung'
    | '/careers'
    | '/contact'
    | '/imprint'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/termin'
    | '/services/$slug'
    | '/api/public/careers-application'
    | '/api/public/consultation-booking'
    | '/api/public/consultation-callback'
    | '/api/public/consultation-manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/beratung'
    | '/careers'
    | '/contact'
    | '/imprint'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/termin'
    | '/services/$slug'
    | '/api/public/careers-application'
    | '/api/public/consultation-booking'
    | '/api/public/consultation-callback'
    | '/api/public/consultation-manage'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/beratung'
    | '/careers'
    | '/contact'
    | '/imprint'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/termin'
    | '/services_/$slug'
    | '/api/public/careers-application'
    | '/api/public/consultation-booking'
    | '/api/public/consultation-callback'
    | '/api/public/consultation-manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BeratungRoute: typeof BeratungRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  ImprintRoute: typeof ImprintRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TerminRoute: typeof TerminRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ApiPublicCareersApplicationRoute: typeof ApiPublicCareersApplicationRoute
  ApiPublicConsultationBookingRoute: typeof ApiPublicConsultationBookingRoute
  ApiPublicConsultationCallbackRoute: typeof ApiPublicConsultationCallbackRoute
  ApiPublicConsultationManageRoute: typeof ApiPublicConsultationManageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termin': {
      id: '/termin'
      path: '/termin'
      fullPath: '/termin'
      preLoaderRoute: typeof TerminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beratung': {
      id: '/beratung'
      path: '/beratung'
      fullPath: '/beratung'
      preLoaderRoute: typeof BeratungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/$slug': {
      id: '/services_/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/consultation-manage': {
      id: '/api/public/consultation-manage'
      path: '/api/public/consultation-manage'
      fullPath: '/api/public/consultation-manage'
      preLoaderRoute: typeof ApiPublicConsultationManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/consultation-callback': {
      id: '/api/public/consultation-callback'
      path: '/api/public/consultation-callback'
      fullPath: '/api/public/consultation-callback'
      preLoaderRoute: typeof ApiPublicConsultationCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/consultation-booking': {
      id: '/api/public/consultation-booking'
      path: '/api/public/consultation-booking'
      fullPath: '/api/public/consultation-booking'
      preLoaderRoute: typeof ApiPublicConsultationBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/careers-application': {
      id: '/api/public/careers-application'
      path: '/api/public/careers-application'
      fullPath: '/api/public/careers-application'
      preLoaderRoute: typeof ApiPublicCareersApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BeratungRoute: BeratungRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  ImprintRoute: ImprintRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TerminRoute: TerminRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ApiPublicCareersApplicationRoute: ApiPublicCareersApplicationRoute,
  ApiPublicConsultationBookingRoute: ApiPublicConsultationBookingRoute,
  ApiPublicConsultationCallbackRoute: ApiPublicConsultationCallbackRoute,
  ApiPublicConsultationManageRoute: ApiPublicConsultationManageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
